version: '3.7'

services:

  db:
    container_name: postgres
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  valkey:
    container_name: valkey
    image: valkey/valkey:8.1
    restart: always
    ports:
      - 6379:6379
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    volumes:
      - valkey_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  valkey_data:

networks:
  backend: